Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -164,32 +164,32 @@ jobs:
           rm -rf Pods Podfile.lock
           pod install --repo-update
 
-      - name: Patch Folly (Post Install)
-        run: |
-          set -e
+      # - name: Patch Folly (Post Install)
+      #   run: |
+      #     set -e
 
-          cd ios
+      #     cd ios
 
-          echo "🔧 Patching Folly..."
+      #     echo "🔧 Patching Folly..."
 
-          FILE="Pods/Headers/Public/RCT-Folly/folly/dynamic.h"
+      #     FILE="Pods/Headers/Public/RCT-Folly/folly/dynamic.h"
 
-          if [ -f "$FILE" ]; then
-            echo "🔧 Patching Folly dynamic.h (symlink-safe)..."
+      #     if [ -f "$FILE" ]; then
+      #       echo "🔧 Patching Folly dynamic.h (symlink-safe)..."
 
-            TMP_FILE=$(mktemp)
+      #       TMP_FILE=$(mktemp)
 
-            # Add missing include
-            sed '1s;^;#include <boost/operators.hpp>\n;' "$FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$FILE"
+      #       # Add missing include
+      #       sed '1s;^;#include <boost/operators.hpp>\n;' "$FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$FILE"
 
-            # Remove boost::operators dependency
-            TMP_FILE=$(mktemp)
-            sed 's/private boost::operators<dynamic>//g' "$FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$FILE"
+      #       # Remove boost::operators dependency
+      #       TMP_FILE=$(mktemp)
+      #       sed 's/private boost::operators<dynamic>//g' "$FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$FILE"
 
-            echo "✅ Folly patch complete"
-          else
-            echo "⚠️ Folly dynamic.h not found — skipping patch"
-          fi
+      #       echo "✅ Folly patch complete"
+      #     else
+      #       echo "⚠️ Folly dynamic.h not found — skipping patch"
+      #     fi
 
       - name: Build iOS (unsigned)
         run: |
