Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,6 +30,18 @@ jobs:
           yarn install --ignore-engines
           yarn jetifier
 
+      - name: Patch react-native-os (compile -> implementation)
+        run: |
+          FILE="node_modules/react-native-os/android/build.gradle"
+          
+          if [ -f "$FILE" ]; then
+            echo "Patching $FILE"
+            sed -i 's/compile /implementation /g' $FILE
+          else
+            echo "File not found: $FILE"
+            exit 1
+          fi
+
       - name: Build Android Release APK
         run: |
           chmod +x android/gradlew
@@ -42,7 +54,6 @@ jobs:
           name: app-release-apk
           path: |
             android/app/build/outputs/apk/release/*.apk
-
 
   build-ios:
     runs-on: macos-latest
@@ -65,6 +76,10 @@ jobs:
         run: |
           yarn install --ignore-engines
           yarn jetifier
+
+      - name: Fix missing FBReactNativeSpec
+        run: |
+          mkdir -p node_modules/react-native/Libraries/FBReactNativeSpec
 
       - name: Install CocoaPods
         run: |
