Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -82,23 +82,38 @@ jobs:
           sudo gem install cocoapods -v 1.16.2
           pod repo update
 
-      - name: Patch boost podspec (safe fix)
+      - name: Fix boost podspec (full safe replacement)
         run: |
           BOOST_SPEC="node_modules/react-native/third-party-podspecs/boost.podspec"
 
           if [ -f "$BOOST_SPEC" ]; then
-            echo "Patching boost podspec safely..."
+            echo "Overwriting boost podspec with fixed version..."
 
-            # Replace ONLY the source URL line
-            sed -i '' "s|:http => .*|:http => 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'|g" "$BOOST_SPEC"
+            printf "Pod::Spec.new do |spec|\n\
+              spec.name = 'boost'\n\
+              spec.version = '1.76.0'\n\
+              spec.license = { :type => 'Boost Software License', :file => 'LICENSE_1_0.txt' }\n\
+              spec.homepage = 'https://www.boost.org'\n\
+              spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'\n\
+              spec.authors = 'Rene Rivera'\n\
+            \n\
+              spec.source = {\n\
+                :http => 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2',\n\
+                :sha256 => '1c162b579a423fa6876c6c5bc16d39ab4bc05e28898977a0a6af345f523f6357'\n\
+              }\n\
+            \n\
+              spec.platforms = { :ios => '11.0', :tvos => '11.0' }\n\
+              spec.requires_arc = false\n\
+            \n\
+              spec.module_name = 'boost'\n\
+              spec.header_dir = 'boost'\n\
+              spec.preserve_paths = 'boost'\n\
+            end\n" > "$BOOST_SPEC"
 
-            # Replace ONLY the checksum line
-            sed -i '' "s|:sha256 => .*|:sha256 => '1c162b579a423fa6876c6c5bc16d39ab4bc05e28898977a0a6af345f523f6357'|g" "$BOOST_SPEC"
-
-          else
-            echo "Boost podspec not found!"
-            exit 1
-          fi
+                else
+                  echo "Boost podspec not found!"
+                  exit 1
+                fi
 
       - name: Install CocoaPods
         run: |
