Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -141,8 +141,8 @@ jobs:
 
       - name: Ensure Boost exists in Pods
         run: |
-          ls -lah ios/Pods/boost/boost_1_76_0/boost || (echo "❌ Boost missing!" && exit 1)
-          ls -lah ios/Pods/boost/boost_1_76_0/libs || (echo "❌ Libs missing!" && exit 1)
+          ls -lah ios/Pods/boost/boost_1_76_0/ || (echo "❌ Boost missing!" && exit 1)
+          
 
       - name: Fix Yoga for Xcode 15
         run: |
